### PR TITLE
add jenkins docker scanning example

### PR DESCRIPTION
**Pull request by tabac-ws**
@lukebroganws pls review

### CODE REVIEW

**Comment by lukebroganws** [comment]
All good, thanks @tabac-ws

**Review by lukebroganws — APPROVED** [review]

**Comment by lukebroganws** [comment]
Just rename to Mend where possible

**Comment by tidharm** [comment]
@tabac-ws I've migrated the changes in this PR to a new PR ([PR #4](https://github.com/mend-toolkit/mend-examples/pull/4)) in the new mend-tookit org.

I copied all the changes as-is, so the new PR still needs to be reviewed independently.

Either way, please halt any further work on this PR (in whitesource-ft) and continue in the new one.
I'm closing this PR.

**Comment by tidharm** [comment]
@tabac-ws I've migrated the changes in this PR to a new PR ([PR #4](https://github.com/mend-toolkit/mend-examples/pull/4)) in the new mend-tookit org.

I copied all the changes as-is, so the new PR still needs to be reviewed independently.

Either way, please halt any further work on this PR (in whitesource-ft) and continue in the new one.
I'm closing this PR.

**Pull request closed without merging**
