### PR TITLE
Aws code build

### PR DESCRIPTION
**Pull request by tabac-ws**
@samq-ws @tidharm pls review

### CODE REVIEW

**Review by lukebroganws — APPROVED** [review]

**Review by samq-ws — CHANGES_REQUESTED** [review]
download an example xcode project from github and test xcode ws-cli

**Comment by tabac-ws** [comment]
> download an example xcode project from github and test xcode ws-cli

I removed the XCode example for now...

**Review by samq-ws — CHANGES_REQUESTED** [review]
buildspec should be renamed to buildspec.yml and product & project name should use codebuild env variables 
https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

**Comment by tabac-ws** [comment]
> buildspec should be renamed to buildspec.yml and product & project name should use codebuild env variables https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

The env variables which can be used are very limited and not related to the pipeline. let's discuss it offline

**Comment by tabac-ws** [comment]
> buildspec should be renamed to buildspec.yml and product & project name should use codebuild env variables https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html

Done - pls review

**Review by samq-ws — APPROVED** [review]

**Pull request merged**
